version: '2'

services:
  web:
    build: ./
    ports:
      - "8083:80"
    restart: unless-stopped
    read_only: true
    tmpfs:
     - /run/apache2
     - /run/lock
     - /usr/local/apache2/logs
